import type { DashboardData, Job, ScanRun, TrackedCompany } from "@/types";

export const ROLE_KEYWORDS = [
  "graduate",
  "intern",
  "internship",
  "summer",
  "trading",
  "trader",
  "quant",
  "quantitative",
  "researcher",
  "research",
  "engineer",
  "software",
] as const;

const seededAt = "2026-06-30T12:00:00.000Z";

export const initialCompanies: TrackedCompany[] = [
  {
    id: "jane-street",
    name: "Jane Street",
    careersUrl: "https://www.janestreet.com/join-jane-street/open-roles/",
    keywords: [...ROLE_KEYWORDS],
    active: true,
    createdAt: seededAt,
    updatedAt: seededAt,
  },
  {
    id: "optiver",
    name: "Optiver",
    careersUrl: "https://optiver.com/working-at-optiver/career-opportunities/",
    keywords: [...ROLE_KEYWORDS],
    active: true,
    createdAt: seededAt,
    updatedAt: seededAt,
  },
  {
    id: "imc",
    name: "IMC",
    careersUrl: "https://www.imc.com/us/careers/jobs/",
    keywords: [...ROLE_KEYWORDS],
    active: true,
    createdAt: seededAt,
    updatedAt: seededAt,
  },
  {
    id: "akuna-capital",
    name: "Akuna Capital",
    careersUrl: "https://akunacapital.com/job-openings/",
    keywords: [...ROLE_KEYWORDS],
    active: true,
    createdAt: seededAt,
    updatedAt: seededAt,
  },
  {
    id: "flow-traders",
    name: "Flow Traders",
    careersUrl: "https://www.flowtraders.com/careers/job-search/",
    keywords: [...ROLE_KEYWORDS],
    active: true,
    createdAt: seededAt,
    updatedAt: seededAt,
  },
  {
    id: "drw",
    name: "DRW",
    careersUrl: "https://www.drw.com/work-at-drw/listings",
    keywords: [...ROLE_KEYWORDS],
    active: true,
    createdAt: seededAt,
    updatedAt: seededAt,
  },
  {
    id: "jump-trading",
    name: "Jump Trading",
    careersUrl: "https://www.jumptrading.com/careers/",
    keywords: [...ROLE_KEYWORDS],
    active: true,
    createdAt: seededAt,
    updatedAt: seededAt,
  },
  {
    id: "citadel-securities",
    name: "Citadel Securities",
    careersUrl: "https://www.citadelsecurities.com/careers/open-opportunities/",
    keywords: [...ROLE_KEYWORDS],
    active: true,
    createdAt: seededAt,
    updatedAt: seededAt,
  },
  {
    id: "sig",
    name: "SIG",
    careersUrl: "https://sig.com/careers/",
    keywords: [...ROLE_KEYWORDS],
    active: true,
    createdAt: seededAt,
    updatedAt: seededAt,
  },
  {
    id: "maven-securities",
    name: "Maven Securities",
    careersUrl: "https://www.mavensecurities.com/careers/",
    keywords: [...ROLE_KEYWORDS],
    active: true,
    createdAt: seededAt,
    updatedAt: seededAt,
  },
  {
    id: "hudson-river-trading",
    name: "Hudson River Trading",
    careersUrl: "https://www.hudsonrivertrading.com/careers/",
    keywords: [...ROLE_KEYWORDS],
    active: true,
    createdAt: seededAt,
    updatedAt: seededAt,
  },
  {
    id: "two-sigma",
    name: "Two Sigma",
    careersUrl: "https://www.twosigma.com/careers/open-roles/",
    keywords: [...ROLE_KEYWORDS],
    active: true,
    createdAt: seededAt,
    updatedAt: seededAt,
  },
  {
    id: "millennium",
    name: "Millennium",
    careersUrl: "https://www.mlp.com/careers/",
    keywords: [...ROLE_KEYWORDS],
    active: true,
    createdAt: seededAt,
    updatedAt: seededAt,
  },
  {
    id: "point72",
    name: "Point72",
    careersUrl: "https://point72.com/careers/",
    keywords: [...ROLE_KEYWORDS],
    active: true,
    createdAt: seededAt,
    updatedAt: seededAt,
  },
  {
    id: "balyasny",
    name: "Balyasny",
    careersUrl: "https://www.bamfunds.com/careers/",
    keywords: [...ROLE_KEYWORDS],
    active: true,
    createdAt: seededAt,
    updatedAt: seededAt,
  },
  {
    id: "tower-research",
    name: "Tower Research Capital",
    careersUrl: "https://www.tower-research.com/open-positions/",
    keywords: [...ROLE_KEYWORDS],
    active: true,
    createdAt: seededAt,
    updatedAt: seededAt,
  },
  {
    id: "five-rings",
    name: "Five Rings",
    careersUrl: "https://fiverings.com/careers/",
    keywords: [...ROLE_KEYWORDS],
    active: true,
    createdAt: seededAt,
    updatedAt: seededAt,
  },
  {
    id: "belvedere-trading",
    name: "Belvedere Trading",
    careersUrl: "https://www.belvederetrading.com/careers/",
    keywords: [...ROLE_KEYWORDS],
    active: true,
    createdAt: seededAt,
    updatedAt: seededAt,
  },
];

export const sampleJobs: Job[] = [
  {
    id: "jane-street-quantitative-trading-intern-summer-2026",
    companyId: "jane-street",
    companyName: "Jane Street",
    title: "Quantitative Trading Intern - Summer 2026",
    location: "New York, London",
    url: "https://www.janestreet.com/join-jane-street/open-roles/",
    sourceUrl: "https://www.janestreet.com/join-jane-street/open-roles/",
    firstSeenAt: "2026-06-27T14:30:00.000Z",
    lastSeenAt: "2026-06-30T12:00:00.000Z",
    status: "new",
    keywordsMatched: ["quantitative", "trading", "intern", "summer"],
    roleType: "internship",
  },
  {
    id: "optiver-quantitative-trader-internship",
    companyId: "optiver",
    companyName: "Optiver",
    title: "Quantitative Trader Internship",
    location: "Chicago",
    url: "https://optiver.com/working-at-optiver/career-opportunities/",
    sourceUrl: "https://optiver.com/working-at-optiver/career-opportunities/",
    firstSeenAt: "2026-06-25T09:20:00.000Z",
    lastSeenAt: "2026-06-30T12:00:00.000Z",
    status: "new",
    keywordsMatched: ["quantitative", "trader", "internship"],
    roleType: "internship",
  },
  {
    id: "imc-graduate-software-engineer",
    companyId: "imc",
    companyName: "IMC",
    title: "Graduate Software Engineer",
    location: "Chicago",
    url: "https://www.imc.com/us/careers/jobs/",
    sourceUrl: "https://www.imc.com/us/careers/jobs/",
    firstSeenAt: "2026-06-24T16:10:00.000Z",
    lastSeenAt: "2026-06-29T18:45:00.000Z",
    status: "seen",
    keywordsMatched: ["graduate", "software", "engineer"],
    roleType: "graduate",
  },
  {
    id: "akuna-quantitative-research-intern",
    companyId: "akuna-capital",
    companyName: "Akuna Capital",
    title: "Quantitative Research Intern",
    location: "Chicago",
    url: "https://akunacapital.com/job-openings/",
    sourceUrl: "https://akunacapital.com/job-openings/",
    firstSeenAt: "2026-06-22T11:15:00.000Z",
    lastSeenAt: "2026-06-29T18:45:00.000Z",
    status: "new",
    keywordsMatched: ["quantitative", "research", "intern"],
    roleType: "internship",
  },
  {
    id: "flow-traders-graduate-trader",
    companyId: "flow-traders",
    companyName: "Flow Traders",
    title: "Graduate Trader",
    location: "Amsterdam",
    url: "https://www.flowtraders.com/careers/job-search/",
    sourceUrl: "https://www.flowtraders.com/careers/job-search/",
    firstSeenAt: "2026-06-20T08:00:00.000Z",
    lastSeenAt: "2026-06-29T18:45:00.000Z",
    status: "seen",
    keywordsMatched: ["graduate", "trader"],
    roleType: "graduate",
  },
  {
    id: "drw-software-developer-intern",
    companyId: "drw",
    companyName: "DRW",
    title: "Software Developer Intern",
    location: "Chicago, Montreal",
    url: "https://www.drw.com/work-at-drw/listings",
    sourceUrl: "https://www.drw.com/work-at-drw/listings",
    firstSeenAt: "2026-06-18T10:25:00.000Z",
    lastSeenAt: "2026-06-28T15:10:00.000Z",
    status: "seen",
    keywordsMatched: ["software", "intern"],
    roleType: "engineering",
  },
  {
    id: "jump-trading-campus-quantitative-researcher",
    companyId: "jump-trading",
    companyName: "Jump Trading",
    title: "Campus Quantitative Researcher",
    location: "New York",
    url: "https://www.jumptrading.com/careers/",
    sourceUrl: "https://www.jumptrading.com/careers/",
    firstSeenAt: "2026-06-17T13:40:00.000Z",
    lastSeenAt: "2026-06-28T15:10:00.000Z",
    status: "new",
    keywordsMatched: ["quantitative", "researcher"],
    roleType: "research",
  },
  {
    id: "citadel-securities-quantitative-research-analyst-intern",
    companyId: "citadel-securities",
    companyName: "Citadel Securities",
    title: "Quantitative Research Analyst Intern",
    location: "New York",
    url: "https://www.citadelsecurities.com/careers/open-opportunities/",
    sourceUrl: "https://www.citadelsecurities.com/careers/open-opportunities/",
    firstSeenAt: "2026-06-16T19:30:00.000Z",
    lastSeenAt: "2026-06-28T15:10:00.000Z",
    status: "applied",
    keywordsMatched: ["quantitative", "research", "intern"],
    roleType: "internship",
  },
  {
    id: "sig-assistant-trader-program",
    companyId: "sig",
    companyName: "SIG",
    title: "Assistant Trader Program",
    location: "Bala Cynwyd",
    url: "https://sig.com/careers/",
    sourceUrl: "https://sig.com/careers/",
    firstSeenAt: "2026-06-15T12:05:00.000Z",
    lastSeenAt: "2026-06-27T20:00:00.000Z",
    status: "ignored",
    keywordsMatched: ["trader"],
    roleType: "trading",
  },
  {
    id: "maven-securities-junior-quantitative-trader",
    companyId: "maven-securities",
    companyName: "Maven Securities",
    title: "Junior Quantitative Trader",
    location: "London",
    url: "https://www.mavensecurities.com/careers/",
    sourceUrl: "https://www.mavensecurities.com/careers/",
    firstSeenAt: "2026-06-14T09:45:00.000Z",
    lastSeenAt: "2026-06-27T20:00:00.000Z",
    status: "new",
    keywordsMatched: ["quantitative", "trader"],
    roleType: "trading",
  },
  {
    id: "hrt-algorithm-developer-intern",
    companyId: "hudson-river-trading",
    companyName: "Hudson River Trading",
    title: "Algorithm Developer Intern",
    location: "New York",
    url: "https://www.hudsonrivertrading.com/careers/",
    sourceUrl: "https://www.hudsonrivertrading.com/careers/",
    firstSeenAt: "2026-06-13T15:15:00.000Z",
    lastSeenAt: "2026-06-27T20:00:00.000Z",
    status: "new",
    keywordsMatched: ["engineer", "intern"],
    roleType: "engineering",
  },
  {
    id: "two-sigma-quantitative-research-intern",
    companyId: "two-sigma",
    companyName: "Two Sigma",
    title: "Quantitative Research Intern",
    location: "New York",
    url: "https://www.twosigma.com/careers/open-roles/",
    sourceUrl: "https://www.twosigma.com/careers/open-roles/",
    firstSeenAt: "2026-06-12T18:35:00.000Z",
    lastSeenAt: "2026-06-27T20:00:00.000Z",
    status: "seen",
    keywordsMatched: ["quantitative", "research", "intern"],
    roleType: "internship",
  },
  {
    id: "millennium-summer-investment-engineering-analyst",
    companyId: "millennium",
    companyName: "Millennium",
    title: "Summer Investment Engineering Analyst",
    location: "New York, London",
    url: "https://www.mlp.com/careers/",
    sourceUrl: "https://www.mlp.com/careers/",
    firstSeenAt: "2026-06-11T12:25:00.000Z",
    lastSeenAt: "2026-06-26T16:40:00.000Z",
    status: "new",
    keywordsMatched: ["summer", "engineer"],
    roleType: "internship",
  },
  {
    id: "point72-academy-investment-analyst-program",
    companyId: "point72",
    companyName: "Point72",
    title: "Academy Investment Analyst Program",
    location: "New York",
    url: "https://point72.com/careers/",
    sourceUrl: "https://point72.com/careers/",
    firstSeenAt: "2026-06-10T14:00:00.000Z",
    lastSeenAt: "2026-06-26T16:40:00.000Z",
    status: "seen",
    keywordsMatched: ["research"],
    roleType: "research",
  },
  {
    id: "balyasny-data-engineer-intern",
    companyId: "balyasny",
    companyName: "Balyasny",
    title: "Data Engineer Intern",
    location: "Chicago",
    url: "https://www.bamfunds.com/careers/",
    sourceUrl: "https://www.bamfunds.com/careers/",
    firstSeenAt: "2026-06-09T10:20:00.000Z",
    lastSeenAt: "2026-06-25T17:30:00.000Z",
    status: "new",
    keywordsMatched: ["engineer", "intern"],
    roleType: "engineering",
  },
  {
    id: "tower-research-quantitative-developer",
    companyId: "tower-research",
    companyName: "Tower Research Capital",
    title: "Quantitative Developer",
    location: "New York",
    url: "https://www.tower-research.com/open-positions/",
    sourceUrl: "https://www.tower-research.com/open-positions/",
    firstSeenAt: "2026-06-08T19:55:00.000Z",
    lastSeenAt: "2026-06-25T17:30:00.000Z",
    status: "seen",
    keywordsMatched: ["quantitative", "engineer"],
    roleType: "quant",
  },
  {
    id: "five-rings-trading-intern",
    companyId: "five-rings",
    companyName: "Five Rings",
    title: "Trading Intern",
    location: "New York",
    url: "https://fiverings.com/careers/",
    sourceUrl: "https://fiverings.com/careers/",
    firstSeenAt: "2026-06-07T11:10:00.000Z",
    lastSeenAt: "2026-06-24T15:45:00.000Z",
    status: "new",
    keywordsMatched: ["trading", "intern"],
    roleType: "internship",
  },
  {
    id: "belvedere-trading-junior-trader",
    companyId: "belvedere-trading",
    companyName: "Belvedere Trading",
    title: "Junior Trader",
    location: "Chicago",
    url: "https://www.belvederetrading.com/careers/",
    sourceUrl: "https://www.belvederetrading.com/careers/",
    firstSeenAt: "2026-06-06T13:05:00.000Z",
    lastSeenAt: "2026-06-24T15:45:00.000Z",
    status: "new",
    keywordsMatched: ["trader"],
    roleType: "trading",
  },
  {
    id: "jane-street-software-engineer-intern",
    companyId: "jane-street",
    companyName: "Jane Street",
    title: "Software Engineer Intern",
    location: "New York, London, Hong Kong",
    url: "https://www.janestreet.com/join-jane-street/open-roles/",
    sourceUrl: "https://www.janestreet.com/join-jane-street/open-roles/",
    firstSeenAt: "2026-06-05T09:35:00.000Z",
    lastSeenAt: "2026-06-23T14:50:00.000Z",
    status: "seen",
    keywordsMatched: ["software", "engineer", "intern"],
    roleType: "engineering",
  },
  {
    id: "optiver-research-scientist-intern",
    companyId: "optiver",
    companyName: "Optiver",
    title: "Research Scientist Intern",
    location: "Amsterdam",
    url: "https://optiver.com/working-at-optiver/career-opportunities/",
    sourceUrl: "https://optiver.com/working-at-optiver/career-opportunities/",
    firstSeenAt: "2026-06-04T08:20:00.000Z",
    lastSeenAt: "2026-06-23T14:50:00.000Z",
    status: "new",
    keywordsMatched: ["research", "intern"],
    roleType: "internship",
  },
  {
    id: "drw-quantitative-trading-analyst",
    companyId: "drw",
    companyName: "DRW",
    title: "Quantitative Trading Analyst",
    location: "Chicago",
    url: "https://www.drw.com/work-at-drw/listings",
    sourceUrl: "https://www.drw.com/work-at-drw/listings",
    firstSeenAt: "2026-06-03T16:45:00.000Z",
    lastSeenAt: "2026-06-22T18:10:00.000Z",
    status: "applied",
    keywordsMatched: ["quantitative", "trading"],
    roleType: "trading",
  },
  {
    id: "sig-software-engineering-internship",
    companyId: "sig",
    companyName: "SIG",
    title: "Software Engineering Internship",
    location: "Bala Cynwyd",
    url: "https://sig.com/careers/",
    sourceUrl: "https://sig.com/careers/",
    firstSeenAt: "2026-06-02T13:25:00.000Z",
    lastSeenAt: "2026-06-22T18:10:00.000Z",
    status: "seen",
    keywordsMatched: ["software", "engineer", "internship"],
    roleType: "engineering",
  },
  {
    id: "citadel-securities-trading-intern",
    companyId: "citadel-securities",
    companyName: "Citadel Securities",
    title: "Trading Intern",
    location: "New York, Chicago",
    url: "https://www.citadelsecurities.com/careers/open-opportunities/",
    sourceUrl: "https://www.citadelsecurities.com/careers/open-opportunities/",
    firstSeenAt: "2026-06-01T09:00:00.000Z",
    lastSeenAt: "2026-06-21T12:30:00.000Z",
    status: "new",
    keywordsMatched: ["trading", "intern"],
    roleType: "internship",
  },
  {
    id: "jump-trading-software-engineering-intern",
    companyId: "jump-trading",
    companyName: "Jump Trading",
    title: "Software Engineering Intern",
    location: "Chicago",
    url: "https://www.jumptrading.com/careers/",
    sourceUrl: "https://www.jumptrading.com/careers/",
    firstSeenAt: "2026-05-31T15:30:00.000Z",
    lastSeenAt: "2026-06-21T12:30:00.000Z",
    status: "seen",
    keywordsMatched: ["software", "engineer", "intern"],
    roleType: "engineering",
  },
];

export const reviewScanJobs: Job[] = [
  {
    id: "review-scan-jane-street-quant-research-intern",
    companyId: "jane-street",
    companyName: "Jane Street",
    title: "Quantitative Research Intern - Newly Detected",
    location: "New York",
    url: "https://www.janestreet.com/join-jane-street/open-roles/",
    sourceUrl: "https://www.janestreet.com/join-jane-street/open-roles/",
    firstSeenAt: "2026-07-01T14:10:00.000Z",
    lastSeenAt: "2026-07-01T14:10:00.000Z",
    status: "new",
    keywordsMatched: ["quantitative", "research", "intern"],
    roleType: "internship",
  },
  {
    id: "review-scan-optiver-graduate-trader",
    companyId: "optiver",
    companyName: "Optiver",
    title: "Graduate Trader - Newly Detected",
    location: "Chicago",
    url: "https://optiver.com/working-at-optiver/career-opportunities/",
    sourceUrl: "https://optiver.com/working-at-optiver/career-opportunities/",
    firstSeenAt: "2026-07-01T14:10:00.000Z",
    lastSeenAt: "2026-07-01T14:10:00.000Z",
    status: "new",
    keywordsMatched: ["graduate", "trader"],
    roleType: "graduate",
  },
  {
    id: "review-scan-hrt-cplusplus-engineer",
    companyId: "hudson-river-trading",
    companyName: "Hudson River Trading",
    title: "C++ Software Engineer - Campus",
    location: "New York",
    url: "https://www.hudsonrivertrading.com/careers/",
    sourceUrl: "https://www.hudsonrivertrading.com/careers/",
    firstSeenAt: "2026-07-01T14:10:00.000Z",
    lastSeenAt: "2026-07-01T14:10:00.000Z",
    status: "new",
    keywordsMatched: ["software", "engineer"],
    roleType: "engineering",
  },
  {
    id: "review-scan-two-sigma-modeling-researcher",
    companyId: "two-sigma",
    companyName: "Two Sigma",
    title: "Quantitative Modeling Researcher - Early Career",
    location: "New York",
    url: "https://www.twosigma.com/careers/open-roles/",
    sourceUrl: "https://www.twosigma.com/careers/open-roles/",
    firstSeenAt: "2026-07-01T14:10:00.000Z",
    lastSeenAt: "2026-07-01T14:10:00.000Z",
    status: "new",
    keywordsMatched: ["quantitative", "researcher"],
    roleType: "research",
  },
  {
    id: "review-scan-flow-traders-trading-intern",
    companyId: "flow-traders",
    companyName: "Flow Traders",
    title: "Trading Intern - Newly Detected",
    location: "Amsterdam",
    url: "https://www.flowtraders.com/careers/job-search/",
    sourceUrl: "https://www.flowtraders.com/careers/job-search/",
    firstSeenAt: "2026-07-01T14:10:00.000Z",
    lastSeenAt: "2026-07-01T14:10:00.000Z",
    status: "new",
    keywordsMatched: ["trading", "intern"],
    roleType: "internship",
  },
  {
    id: "review-scan-tower-research-intern",
    companyId: "tower-research",
    companyName: "Tower Research Capital",
    title: "Quantitative Developer Intern - Newly Detected",
    location: "New York",
    url: "https://www.tower-research.com/open-positions/",
    sourceUrl: "https://www.tower-research.com/open-positions/",
    firstSeenAt: "2026-07-01T14:10:00.000Z",
    lastSeenAt: "2026-07-01T14:10:00.000Z",
    status: "new",
    keywordsMatched: ["quantitative", "engineer", "intern"],
    roleType: "internship",
  },
];

export const sampleScanRuns: ScanRun[] = [
  {
    id: "sample-scan-2026-06-30",
    startedAt: "2026-06-30T11:58:00.000Z",
    completedAt: "2026-06-30T12:00:00.000Z",
    status: "partial",
    companiesChecked: 18,
    jobsFound: 24,
    newJobsAdded: 9,
    errors: [
      {
        companyId: "maven-securities",
        companyName: "Maven Securities",
        url: "https://www.mavensecurities.com/careers/",
        message:
          "Sample limitation: site may block automated reads or require manual review.",
      },
    ],
  },
  {
    id: "sample-scan-2026-06-29",
    startedAt: "2026-06-29T11:58:00.000Z",
    completedAt: "2026-06-29T12:01:00.000Z",
    status: "completed",
    companiesChecked: 18,
    jobsFound: 24,
    newJobsAdded: 7,
    errors: [],
  },
  {
    id: "sample-scan-2026-06-28",
    startedAt: "2026-06-28T11:58:00.000Z",
    completedAt: "2026-06-28T12:02:00.000Z",
    status: "partial",
    companiesChecked: 18,
    jobsFound: 21,
    newJobsAdded: 5,
    errors: [
      {
        companyId: "flow-traders",
        companyName: "Flow Traders",
        url: "https://www.flowtraders.com/careers/job-search/",
        message: "Sample limitation: dynamic listings required manual review.",
      },
    ],
  },
];

export const sampleDashboardData: DashboardData = {
  companies: initialCompanies,
  jobs: sampleJobs,
  scanRuns: sampleScanRuns,
  mode: "sample",
};
