import type { DashboardData, Job, ScanRun, TrackedCompany } from "@/types";

export const ROLE_KEYWORDS = [
  "graduate",
  "intern",
  "internship",
  "summer",
  "trading",
  "trader",
  "quant",
  "quantitative",
  "researcher",
  "research",
  "engineer",
  "software",
] as const;

const seededAt = "2026-06-30T12:00:00.000Z";

export const initialCompanies: TrackedCompany[] = [
  {
    id: "jane-street",
    name: "Jane Street",
    careersUrl: "https://www.janestreet.com/join-jane-street/open-roles/",
    keywords: [...ROLE_KEYWORDS],
    active: true,
    createdAt: seededAt,
    updatedAt: seededAt,
  },
  {
    id: "optiver",
    name: "Optiver",
    careersUrl: "https://optiver.com/working-at-optiver/career-opportunities/",
    keywords: [...ROLE_KEYWORDS],
    active: true,
    createdAt: seededAt,
    updatedAt: seededAt,
  },
  {
    id: "imc",
    name: "IMC",
    careersUrl: "https://www.imc.com/us/careers/jobs/",
    keywords: [...ROLE_KEYWORDS],
    active: true,
    createdAt: seededAt,
    updatedAt: seededAt,
  },
  {
    id: "akuna-capital",
    name: "Akuna Capital",
    careersUrl: "https://akunacapital.com/job-openings/",
    keywords: [...ROLE_KEYWORDS],
    active: true,
    createdAt: seededAt,
    updatedAt: seededAt,
  },
  {
    id: "flow-traders",
    name: "Flow Traders",
    careersUrl: "https://www.flowtraders.com/careers/job-search/",
    keywords: [...ROLE_KEYWORDS],
    active: true,
    createdAt: seededAt,
    updatedAt: seededAt,
  },
  {
    id: "drw",
    name: "DRW",
    careersUrl: "https://www.drw.com/work-at-drw/listings",
    keywords: [...ROLE_KEYWORDS],
    active: true,
    createdAt: seededAt,
    updatedAt: seededAt,
  },
  {
    id: "jump-trading",
    name: "Jump Trading",
    careersUrl: "https://www.jumptrading.com/careers/",
    keywords: [...ROLE_KEYWORDS],
    active: true,
    createdAt: seededAt,
    updatedAt: seededAt,
  },
  {
    id: "citadel-securities",
    name: "Citadel Securities",
    careersUrl: "https://www.citadelsecurities.com/careers/open-opportunities/",
    keywords: [...ROLE_KEYWORDS],
    active: true,
    createdAt: seededAt,
    updatedAt: seededAt,
  },
  {
    id: "sig",
    name: "SIG",
    careersUrl: "https://sig.com/careers/",
    keywords: [...ROLE_KEYWORDS],
    active: true,
    createdAt: seededAt,
    updatedAt: seededAt,
  },
  {
    id: "maven-securities",
    name: "Maven Securities",
    careersUrl: "https://www.mavensecurities.com/careers/",
    keywords: [...ROLE_KEYWORDS],
    active: true,
    createdAt: seededAt,
    updatedAt: seededAt,
  },
];

export const sampleJobs: Job[] = [
  {
    id: "jane-street-quantitative-trading-intern-summer-2026",
    companyId: "jane-street",
    companyName: "Jane Street",
    title: "Quantitative Trading Intern - Summer 2026",
    location: "New York, London",
    url: "https://www.janestreet.com/join-jane-street/open-roles/",
    sourceUrl: "https://www.janestreet.com/join-jane-street/open-roles/",
    firstSeenAt: "2026-06-27T14:30:00.000Z",
    lastSeenAt: "2026-06-30T12:00:00.000Z",
    status: "new",
    keywordsMatched: ["quantitative", "trading", "intern", "summer"],
    roleType: "internship",
  },
  {
    id: "optiver-quantitative-trader-internship",
    companyId: "optiver",
    companyName: "Optiver",
    title: "Quantitative Trader Internship",
    location: "Chicago",
    url: "https://optiver.com/working-at-optiver/career-opportunities/",
    sourceUrl: "https://optiver.com/working-at-optiver/career-opportunities/",
    firstSeenAt: "2026-06-25T09:20:00.000Z",
    lastSeenAt: "2026-06-30T12:00:00.000Z",
    status: "new",
    keywordsMatched: ["quantitative", "trader", "internship"],
    roleType: "internship",
  },
  {
    id: "imc-graduate-software-engineer",
    companyId: "imc",
    companyName: "IMC",
    title: "Graduate Software Engineer",
    location: "Chicago",
    url: "https://www.imc.com/us/careers/jobs/",
    sourceUrl: "https://www.imc.com/us/careers/jobs/",
    firstSeenAt: "2026-06-24T16:10:00.000Z",
    lastSeenAt: "2026-06-29T18:45:00.000Z",
    status: "seen",
    keywordsMatched: ["graduate", "software", "engineer"],
    roleType: "graduate",
  },
  {
    id: "akuna-quantitative-research-intern",
    companyId: "akuna-capital",
    companyName: "Akuna Capital",
    title: "Quantitative Research Intern",
    location: "Chicago",
    url: "https://akunacapital.com/job-openings/",
    sourceUrl: "https://akunacapital.com/job-openings/",
    firstSeenAt: "2026-06-22T11:15:00.000Z",
    lastSeenAt: "2026-06-29T18:45:00.000Z",
    status: "new",
    keywordsMatched: ["quantitative", "research", "intern"],
    roleType: "internship",
  },
  {
    id: "flow-traders-graduate-trader",
    companyId: "flow-traders",
    companyName: "Flow Traders",
    title: "Graduate Trader",
    location: "Amsterdam",
    url: "https://www.flowtraders.com/careers/job-search/",
    sourceUrl: "https://www.flowtraders.com/careers/job-search/",
    firstSeenAt: "2026-06-20T08:00:00.000Z",
    lastSeenAt: "2026-06-29T18:45:00.000Z",
    status: "seen",
    keywordsMatched: ["graduate", "trader"],
    roleType: "graduate",
  },
  {
    id: "drw-software-developer-intern",
    companyId: "drw",
    companyName: "DRW",
    title: "Software Developer Intern",
    location: "Chicago, Montreal",
    url: "https://www.drw.com/work-at-drw/listings",
    sourceUrl: "https://www.drw.com/work-at-drw/listings",
    firstSeenAt: "2026-06-18T10:25:00.000Z",
    lastSeenAt: "2026-06-28T15:10:00.000Z",
    status: "seen",
    keywordsMatched: ["software", "intern"],
    roleType: "engineering",
  },
  {
    id: "jump-trading-campus-quantitative-researcher",
    companyId: "jump-trading",
    companyName: "Jump Trading",
    title: "Campus Quantitative Researcher",
    location: "New York",
    url: "https://www.jumptrading.com/careers/",
    sourceUrl: "https://www.jumptrading.com/careers/",
    firstSeenAt: "2026-06-17T13:40:00.000Z",
    lastSeenAt: "2026-06-28T15:10:00.000Z",
    status: "new",
    keywordsMatched: ["quantitative", "researcher"],
    roleType: "research",
  },
  {
    id: "citadel-securities-quantitative-research-analyst-intern",
    companyId: "citadel-securities",
    companyName: "Citadel Securities",
    title: "Quantitative Research Analyst Intern",
    location: "New York",
    url: "https://www.citadelsecurities.com/careers/open-opportunities/",
    sourceUrl: "https://www.citadelsecurities.com/careers/open-opportunities/",
    firstSeenAt: "2026-06-16T19:30:00.000Z",
    lastSeenAt: "2026-06-28T15:10:00.000Z",
    status: "applied",
    keywordsMatched: ["quantitative", "research", "intern"],
    roleType: "internship",
  },
  {
    id: "sig-assistant-trader-program",
    companyId: "sig",
    companyName: "SIG",
    title: "Assistant Trader Program",
    location: "Bala Cynwyd",
    url: "https://sig.com/careers/",
    sourceUrl: "https://sig.com/careers/",
    firstSeenAt: "2026-06-15T12:05:00.000Z",
    lastSeenAt: "2026-06-27T20:00:00.000Z",
    status: "ignored",
    keywordsMatched: ["trader"],
    roleType: "trading",
  },
  {
    id: "maven-securities-junior-quantitative-trader",
    companyId: "maven-securities",
    companyName: "Maven Securities",
    title: "Junior Quantitative Trader",
    location: "London",
    url: "https://www.mavensecurities.com/careers/",
    sourceUrl: "https://www.mavensecurities.com/careers/",
    firstSeenAt: "2026-06-14T09:45:00.000Z",
    lastSeenAt: "2026-06-27T20:00:00.000Z",
    status: "new",
    keywordsMatched: ["quantitative", "trader"],
    roleType: "trading",
  },
];

export const sampleScanRuns: ScanRun[] = [
  {
    id: "sample-scan-2026-06-30",
    startedAt: "2026-06-30T11:58:00.000Z",
    completedAt: "2026-06-30T12:00:00.000Z",
    status: "partial",
    companiesChecked: 10,
    jobsFound: 10,
    newJobsAdded: 4,
    errors: [
      {
        companyId: "maven-securities",
        companyName: "Maven Securities",
        url: "https://www.mavensecurities.com/careers/",
        message:
          "Sample limitation: site may block automated reads or require manual review.",
      },
    ],
  },
];

export const sampleDashboardData: DashboardData = {
  companies: initialCompanies,
  jobs: sampleJobs,
  scanRuns: sampleScanRuns,
  mode: "sample",
};
